CREATE TABLE USERS (
	NAME    	VARCHAR(10) NOT NULL PRIMARY KEY,
	PASSWORD    VARCHAR(8) NOT NULL,
	NICKNAME    VARCHAR(20) UNIQUE,
	DESCRIPTION VARCHAR(50),
	PHOTO       VARCHAR(150)
);

CREATE TABLE CHANNELS (
	NAME 		VARCHAR(30) PRIMARY KEY,
	DESCRIPTION VARCHAR(500) NOT NULL,
	CREATEDBY 	VARCHAR(10) NOT NULL,
	CREATED 	TIMESTAMP NOT NULL,
	SUBSCRIBERS INTEGER
);

CREATE TABLE SUBSCRIPTIONS (
	ID 			INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	USER 		VARCHAR(10) NOT NULL REFERENCES USERS(NICKNAME) ON DELETE CASCADE,
	CHANNEL 	VARCHAR(30) NOT NULL REFERENCES CHANNELS(NAME) ON DELETE CASCADE
);

CREATE TABLE MESSAGES (
	ID 			INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	TEXT 		VARCHAR(500) NOT NULL,
	SENDER 		VARCHAR(10) NOT NULL REFERENCES USERS(NAME) ON DELETE CASCADE,
	RECEIVER 	VARCHAR(10) REFERENCES USERS(NAME) ON DELETE CASCADE,
	CHANNEL 	VARCHAR(30) REFERENCES CHANNELS(NAME) ON DELETE CASCADE,
	REPLYFOR 	INTEGER REFERENCES MESSAGES(ID) ON DELETE CASCADE,
	SENT 		TIMESTAMP NOT NULL
);